const UPDATE_SEARCH_STRING_ACTION = 'UPDATE_SEARCH_STRING'
const SEARCH_RESULT_INIT_ACTION = 'SEARCH_RESULT_INIT'
const SEARCH_RESULT_RECEIVED_ACTION = 'SEARCH_RESULT_RECEIVED'
const ADD_USER_DETAILS_ACTION = 'ADD_USER_DETAILS'
const NEXT_RESULT_INIT_ACTION = 'NEXT_RESULT_INIT'
const NEXT_RESULT_RECEIVED_ACTION = 'NEXT_RESULT_RECEIVED'
const CLEAR_SEARCH_RESULT_ACTION = 'CLEAR_SEARCH_RESULT'
const ADD_USER_FOLLOWER_COUNT_ACTION = 'ADD_USER_FOLLOWER_COUNT'
const ADD_USER_FOLLOWING_COUNT_ACTION = 'ADD_USER_FOLLOWING_COUNT'

export {
  UPDATE_SEARCH_STRING_ACTION,
  SEARCH_RESULT_INIT_ACTION,
  SEARCH_RESULT_RECEIVED_ACTION,
  ADD_USER_DETAILS_ACTION,
  NEXT_RESULT_INIT_ACTION,
  NEXT_RESULT_RECEIVED_ACTION,
  CLEAR_SEARCH_RESULT_ACTION,
  ADD_USER_FOLLOWER_COUNT_ACTION,
  ADD_USER_FOLLOWING_COUNT_ACTION,
}
